name: Sale Tracker

on:
  schedule:
    - cron: '*/120 * * * *'

  workflow_dispatch:

jobs:
  track-sale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Check for job openings
      run: |
        cd src
        python sale_tracker.py

